CC = gcc
CFLAGS = -Wall -g
PROJ_PATH = ./src
OBJECTS = hash_map.o  main.o

LDFLAGS = 

all: main

main: $(OBJECTS)
	$(CC) $^ $(LDFLAGS) -o $@

main.o: $(PROJ_PATH)/main.c
	$(CC) $(CFLAGS) $^ -c

hash_map.o: $(PROJ_PATH)/hash_map.c $(PROJ_PATH)/hash_map.h
	$(CC) $(CFLAGS) $^ -c

clean:
	rm -f *.o main
